version: "3.8"
services:
  bigceline:
    image: bigceline/bigceline:latest
    env_file: ./.env
    command: node index.js
  watchtower:
    image: containrrr/watchtower
    env_file: ./.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    command: --cleanup --interval 30
