scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080

- job_name: bigceline
  scrape_interval: 5s
  static_configs:
  - targets:
    - bigceline:6060
